name: Mendix App Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Mono and OpenJDK 11
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete
        sudo apt install -y openjdk-11-jdk

    - name: Cache Mendix mxbuild
      uses: actions/cache@v2
      with:
        path: mxbuild-9.18.4.62522
        key: mxbuild-9.18.4.62522

    - name: Download and extract mxbuild
      run: |
        if [ ! -d "mxbuild-9.18.4.62522" ]; then
          wget https://cdn.mendix.com/runtime/mxbuild-9.18.4.62522.tar.gz
          mkdir mxbuild-9.18.4.62522
          tar -xzf mxbuild-9.18.4.62522.tar.gz -C mxbuild-9.18.4.62522
        fi

    - name: Show Mendix version
      run: |
        mono mxbuild-9.18.4.62522/modeler/mx.exe show-version Mendix9184Empty.mpr

    - name: Build Mendix project
      run: |
        mono mxbuild-9.18.4.62522/modeler/mxbuild.exe --java-home="/usr/lib/jvm/java-11-openjdk-amd64/" --java-exe-path="/usr/lib/jvm/java-11-openjdk-amd64/bin/java" Mendix9184Empty.mpr

    - name: "Release MDA Files"
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: false
         unprotected: true
         title: "Mendix deploy achieve"
         files: |
              *.mda
